### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by snayfach** [ytomofuji/JMAG_JVD#1]
wget ftp://ftp.ddbj.nig.ac.jp/ddbj_database/wgs/EM/EMNW.gz

> --2022-12-25 10:17:02--  ftp://ftp.ddbj.nig.ac.jp/ddbj_database/wgs/EM/EMNW.gz
>            => 'EMNW.gz'
> Resolving ftp.ddbj.nig.ac.jp (ftp.ddbj.nig.ac.jp)... 133.39.24.50
> Connecting to ftp.ddbj.nig.ac.jp (ftp.ddbj.nig.ac.jp)|133.39.24.50|:21... connected.
> Logging in as anonymous ... Logged in!
> ==> SYST ... done.    ==> PWD ... done.
> ==> TYPE I ... done.  ==> CWD (1) /ddbj_database/wgs/EM ...
> No such directory 'ddbj_database/wgs/EM'

The other file downloads without errors. Any idea what's wrong?

**Comment by ytomofuji** [comment]
We apologize for the inconvenience.
The error you mentioned has been reproduced on our side as well.
Can you please try 'wget ftp://ftp.ddbj.nig.ac.jp/ddbj_database/tpa/wgs/EM/EMNW.gz'?
I have just confirmed that this URL worked.

We will also check and update the ULR list to see if anything is no longer working.
Thank you for pointing that out.

**Comment by snayfach** [comment]
Yes, that file works. There are 28816 sequences in BRDB.gz and 2579 in EMNW.gz for a total of 31395, which matches the number from the publication. Many thanks!
